# create your drupal and postgres config here, based off the last assignment

version: '3.1'

services:
 
  drupal: 
    image: drupal:8.2
    ports:
     - 80:80
    deploy:
      replicas: 3

  postgres:
    image: postgres:10
    secrets:
     - user_id
     - password
    volumes:
     - drupal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/user_id
      POSTGRES_PASSWORD_FILE: /run/secrets/password

volumes:
  drupal-data:

secrets:
  user_id:
    external: true

  password:
    external: true
